In [17]:
!pip install requests pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [18]:
import requests
import pandas as pd
import sqlite3

In [19]:
url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "api_key": API_KEY,
    "language": "en-US",
    "sort_by": "popularity.desc",
    "page": 1
}
response = requests.get(url, params=params)
data = response.json()
movies = data["results"]
len(movies)

20

In [20]:
df = pd.DataFrame(movies)
df = df[[
    "id",
    "title",
    "release_date",
    "popularity",
    "vote_average",
    "vote_count",
    "genre_ids"
]]
df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,1165.1266,6.827,26,"[10749, 18]"
1,83533,Avatar: Fire and Ash,2025-12-17,503.6662,7.309,2084,"[878, 12, 14]"
2,1115544,Mike & Nick & Nick & Alice,2026-03-14,352.9397,6.700,109,"[35, 878, 80]"
3,1084187,Pretty Lethal,2026-03-13,311.0726,6.745,159,"[28, 53, 10402]"
4,1290821,Shelter,2026-01-28,308.3847,6.751,442,"[28, 80, 53]"

In [21]:
import sqlite3
df["genre_ids"] = df["genre_ids"].astype(str)
conn = sqlite3.connect("movies.db")
df.to_sql("movies", conn, if_exists="replace", index=False)
print("Data stored in SQLite database")

Data stored in SQLite database

In [22]:
movies_df = pd.read_sql("SELECT * FROM movies", conn)
movies_df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,1165.1266,6.827,26,"[10749, 18]"
1,83533,Avatar: Fire and Ash,2025-12-17,503.6662,7.309,2084,"[878, 12, 14]"
2,1115544,Mike & Nick & Nick & Alice,2026-03-14,352.9397,6.700,109,"[35, 878, 80]"
3,1084187,Pretty Lethal,2026-03-13,311.0726,6.745,159,"[28, 53, 10402]"
4,1290821,Shelter,2026-01-28,308.3847,6.751,442,"[28, 80, 53]"

In [23]:
movies_df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,1165.1266,6.827,26,"[10749, 18]"
1,83533,Avatar: Fire and Ash,2025-12-17,503.6662,7.309,2084,"[878, 12, 14]"
2,1115544,Mike & Nick & Nick & Alice,2026-03-14,352.9397,6.700,109,"[35, 878, 80]"
3,1084187,Pretty Lethal,2026-03-13,311.0726,6.745,159,"[28, 53, 10402]"
4,1290821,Shelter,2026-01-28,308.3847,6.751,442,"[28, 80, 53]"

In [24]:
movies_df.describe()

                 id   popularity  vote_average   vote_count
count  2.000000e+01    20.000000     20.000000    20.000000
mean   1.062134e+06   263.099260      6.933350   590.200000
std    3.097655e+05   234.540901      0.811891   658.347261
min    8.353300e+04   101.340400      5.200000     2.000000
25%    8.789158e+05   151.561075      6.479750   146.500000
50%    1.137552e+06   181.292600      6.913500   400.000000
75%    1.271912e+06   300.460725      7.389000   763.250000
max    1.523145e+06  1165.126600      8.500000  2411.000000

In [25]:
movies_df["genre_ids"].explode().value_counts()

genre_ids
[10749, 18]                  2
[878, 12, 14]                1
[35, 878, 80]                1
[28, 53, 10402]              1
[28, 80, 53]                 1
[16, 35, 10751]              1
[878, 12]                    1
[27, 9648, 80]               1
[27, 53, 35]                 1
[12, 53, 878]                1
[28, 878, 53]                1
[80, 53]                     1
[80, 18]                     1
[18]                         1
[35, 18, 10751, 10749]       1
[16, 10751, 878, 35, 12]     1
[16, 35, 12, 10751, 9648]    1
[27]                         1
[27, 9648]                   1
Name: count, dtype: int64

In [26]:
movies_df.isnull().sum()

id              0
title           0
release_date    0
popularity      0
vote_average    0
vote_count      0
genre_ids       0
dtype: int64

In [27]:
conn.close()